### ISSUE TITLE
For which Amazon file type?

### ISSUE THREAD

**Issue by luxlux** [ZaidoR1/bookwork#1]
nice to find something like this here on github ... :)

you write:

> Creates DATEV-File for Amazon
> `node amazon.js /path/to/amazon_transaction_file/14487840203017910.txt`

I have checked the file from "Umsatzsteuerberechnungsservice", 
also the file which can be downloaded in "Zahlungen", "Transaktionsansicht" 
and the file which can be created in "Berichte nach Zeitraum" (Art:"Transaktion").
In none of these is "Marketplace" in column 3.

Which type of amazon file do you process?

**Comment by ZaidoR1** [comment]
Hey, sorry for my late replay.
Go to "Berichte -> Steuerdokumente", then "Amazon Umsatzsteuer-Transaktionsberichte ansehen". There you can create a report for a whole month.
Hope that helped.
<img width="756" alt="Bildschirmfoto 2019-06-12 um 22 31 02" src="https://user-images.githubusercontent.com/16700058/59384174-e3850300-8d61-11e9-8c36-ced8fa2cbc89.png">

**Comment by luxlux** [comment]
Alles klar, danke für die Rückmeldung. Ja mit diesem Bericht funktioniert es.
Ich hatte es mit dem Bericht des Umsatzsteuerberechnungsservice versucht. 
Aber der Umsatzsteuer-Transaktionsbericht scheint auch die notwendigen Daten zu enthalten.

Um das ganze individuell anpassen zu können hatte ich mich noch gefragt um was für ein DATEV Format es sich handelt. Aber das vermute ich inzwischen auch herausgefunden zu haben: 
Es ist das inzwischen abgekündigte "Postversandformat" (KNE) als Buchungsstapel, das wohl ab 2019 nicht mehr von DATEV unterstützt wird, aber bei Bedarf als individuelles ASCII [wieder angelegt werden kann](https://www.datev-community.de/thread/7082). (Richtig?)

Die Bedeutung der einzelnen Spalten ist [hier](https://apps.datev.de/dnlexka/#/document/1003221) unter Punkt 3 beschrieben. (Falls sich das noch jemand anderes Fragen sollte.)

**Comment by luxlux** [comment]
Die Feld Nummer von PRICE_OF_ITEMS_VAT_RATE_PERCENT ist falsch angegeben. Es ist die 29 nicht die 30.
In deiner Umwandlung sollte sich dieser Fehler nicht ausgewirkt haben, da auch der Wert in 30 (PRICE_OF_ITEMS_VAT_AMT) geeignet ist, wenn es nur darum geht auf !== 0 zu prüfen.

Ich benötige allerdings eine Unterscheidung zwischen 7% und 19%, daher ist's mir aufgefallen.

**Comment by ZaidoR1** [comment]
Ich verwende mittlerweile dieses Programm nicht mehr. Habe meinen Steuerberater gewechselt, welcher sich speziell auf Amazon konzentiert.
Aber da hast du recht, 19%/7% unterscheide ich nicht, weil das für mich keine Rolle spielte. Wenn du magst, kannst du gerne die Änderungen vornehmen :)

**Comment by luxlux** [comment]
Ja, es gab auch in meinem Kontext auch noch einige andere Unzulänglichkeiten. 
Ich habe mir das ganze inzwischen für mich angepasst und auch erweitert um eine summarische Auswertung, nach Abgangs VAT Nummern, Lieferländern, Steuersätzen, steuerfreien EU Lieferungen, NON EU Exporten bis hin zur Generierung von CSVs für die Zusammenfassende Meldung von steuerfreien EU Lieferungen. 

Das war mir zum einen zu Kontrollzwecken wichtig, um zu wissen, was überhaupt in den Amazon Rechnungen steht. Auch erstelle die Umsatzsteuervoranmeldungen unterjährig selbst. Das kostet etwa genauso viel Zeit wie zweimontalich die Unterlagen nur für den Steuerberater zusammenzutragen, aber ich behalte dabei selbst auch den Überblick über die Dimensionen und kann ggf. gezielt nachfragen, wenn der Sachbearbeiter im Steuerbüro etwas falsch interpretiert oder gar vergisst. Der bekommt das ganze vergangene Jahr dann von mir auf einmal, arbeitet es mit seinem Profi Wissen ab und nimmt ggf. entsprechend auch Korrekturmeldungen vor, wo ich die Lage nicht richtig eingeschätzt habe.

In jedem Fall war Dein Tool zumindest ein guter Einstiegspunkt in die CSV Verarbeitung und den DATEV Ascii Export für mich. Vielen Dank dafür.

**Comment by ZaidoR1** [comment]
Freut mich, wenn dir das Tool helfen konnte, so sollte es sein :)
